export interface Post {
  title: string;
  hashtag: string[];
  user: string;
  view: number;
}
export const data: Post[] = [
  {
    title: "네이버 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 1,
  },
  {
    title: "카카오 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 2,
  },
  {
    title: "라인 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 3,
  },
  {
    title: "쿠팡 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 4,
  },
  {
    title: "배민 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 5,
  },
  {
    title: "토스 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 6,
  },
  {
    title: "당근 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 7,
  },
  {
    title: "직방 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 8,
  },
  {
    title: "네이버 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 9,
  },
  {
    title: "카카오 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 10,
  },
  {
    title: "라인 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 11,
  },
  {
    title: "쿠팡 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 12,
  },
  {
    title: "배민 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 13,
  },
  {
    title: "토스 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 14,
  },
  {
    title: "당근 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 15,
  },
  {
    title: "직방 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 16,
  },
  {
    title: "네이버 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 17,
  },
  {
    title: "카카오 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 18,
  },
  {
    title: "라인 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "쿠팡 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 20,
  },
  {
    title: "배민 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "토스 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "당근 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "직방 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "네이버 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "카카오 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "라인 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "쿠팡 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 30,
  },
  {
    title: "배민 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "토스 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "당근 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "직방 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "네이버 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "카카오 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "라인 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "쿠팡 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "배민 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "토스 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "당근 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "직방 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "네이버 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "카카오 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "라인 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "쿠팡 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "배민 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "토스 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "당근 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
  {
    title: "END 1차",
    hashtag: ["네트워크", "운영체제"],
    user: "hyodori",
    view: 300,
  },
];
