name: nCloud Deployment

on:
  push:
    branches: "main"
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: ${{ secrets.SSH_SCRIPT }}

  deploy-production-front:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy FrontServer
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST_FRONT_ALPAKA}}
          username: ${{secrets.SSH_USERNAME_FRONT_ALPAKA}}
          password: ${{secrets.SSH_PASSWORD_FRONT_ALPAKA}}
          port: ${{secrets.SSH_PORT_FRONT_ALPAKA}}
          script: |
            cd ~/web23_MoMyeon/frontend
            git pull
            touch .env
            echo ${{secrets.ENV_CONTENT_FRONT}} >> .env
            yarn install
            yarn build
            pm2 delete front-server
            pm2 --name 'front-server' start yarn -- start
            cd ~/web23_MoMyeon/mediaServer
            yarn install
            pm2 delete media-server
            pm2 --name 'media-server' start node server.js
